# Generated by Django 5.0.2 on 2025-09-12 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_collection_product_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='pieces',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='pieces',
        ),
    ]
